### ISSUE TITLE
Question about script style

### ISSUE THREAD

**Issue by brettp** [wick3dr0se/archstrap#4]
Thanks for the script! This isn't an issue, but a question about the style. I notice this pattern is used often:

```bash
: "string"
use_string "$_"
```

For example, [`arch_chroot`](https://github.com/wick3dr0se/archstrap/blob/7e4f09d79780ef7a6d34611671cc2b2658ecbf26/archstrap#L37) and [L46](https://github.com/wick3dr0se/archstrap/blob/7e4f09d79780ef7a6d34611671cc2b2658ecbf26/archstrap#L46C1-L47C66):

```bash
: "iso/latest"
get_tarball "$globalMirror/$_/$tarBall" "$officialURL/$_/$tarSig"
```

I understand what the code does, but am curious about the style. Could you tell me more about it? Are there advantages to using this approach instead of something like:

```bash
release="iso/latest"
get_tarball "$globalMirror/$release/$tarBall" "$officialURL/$release/$tarSig"
```

Thanks!

**Comment by wick3dr0se** [comment]
@brettp Hey, thank you! I love when people check the code out and have questions about it, no worries! 😄 So I am just using the _ variable as way to temporarily hold repitive strings

```bash
arch_chroot(){
  : "$rootFS"
  mountpoint "$_" >/dev/null|| mount --bind "$_" "$_"
  "$_/bin/arch-chroot" "$_" "$@"
}
```

Like here; Otherwise I would be calling $rootFS 5 times and it just seemed excessive to me. I do know _ is commonly used for discarding but I use it a ton for things like reading command line arguments even. My project bashin uses them everywhere. I kind of just code things for my prefrence and depending on if I think anyone will contribute to the project. If anyone does I'm always open to adjustments!
