### ISSUE TITLE
What does mountpoint and output_name mean?

### ISSUE THREAD

**Issue by TurnOffNOD** [wick3dr0se/archstrap#8]
In README, it says:

> Execution
> 
> ./archstrap [mountpoint] [output_name]

What dows parameter `mountpoint` and `output_name` mean? Is there any explanation?

**Comment by pabryan** [comment]
The script creates a root filesystem and then chroots there.

The root filesystem is created in `[mountpoint]/[output_name]`. If you omit `output_name`, it defaults to "archrootfs". If you omit any arguments, `mountpoint` is a temporary directory: it's `$TMPDIR` if that is set, otherwise `$XDG_RUNTIME_DIR` if that is set, or finally `/tmp` as a fail safe.

There's probably no need for both `mountpoint` and `output_name`. It would suffice to just use `mountpoint` if set, or "archrootfs" in the tmp directory if no argument is passed.

**Comment by wick3dr0se** [comment]
Yes and thanks to your comment, I added some clarification in the README.md!

Just as @pabryan said.. `mountpoint` and `output_name`, now `rootfs_name`, are completely optional arguments (`[]`)
